### ISSUE TITLE
Clock Durability?

### ISSUE THREAD

**Issue by cntrik** [TheMegax/Chronos-Mod#1]
Could you add a durability option to the Chronos' Clock? Otherwise thank you for this great mod gonna incorporate it within my modpack.

**Comment by TheMegax** [comment]
Hey thanks! There's a durability option in the config menu either by using mod menu + cloth config or directly editing `.minecraft/config/chronos.conf` ;]

Edit: Just to clarify, "0" durability is unbreakable and durability changes won't be reflected until restart
