### ISSUE TITLE
Time In A Bottle Compat?

### ISSUE THREAD

**Issue by cntrik** [TheMegax/Chronos-Mod#3]
Due to how [Time In A Bottle](https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle) changes block tick speed it's currently does not properly apply to block tiles completely nullifying the tick speed increase, so would there be any plans of compat or implementation of your own item?
The mod itself falls under a MIT license

**Comment by TheMegax** [comment]
I'll look into it, I believe the Time in a Bottle mod is directly using vanilla's tick function which is overridden by this mod. Thanks!

**Comment by TheMegax** [comment]
Heya, I tested the Time in a Bottle mod a bit with spawners and furnaces and everything worked fine. Did you use the item with a modded block entity?
